// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sunflower-blog-svc/internal/biz"
	"sunflower-blog-svc/internal/conf"
	"sunflower-blog-svc/internal/data"
	"sunflower-blog-svc/internal/server"
	"sunflower-blog-svc/internal/service/poster"
	"sunflower-blog-svc/internal/service/user"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewPostgresDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	posterRepo := data.NewPosterRepo(dataData, logger)
	posterUseCase := biz.NewPosterUseCase(posterRepo, logger)
	service := poster.NewPosterService(posterUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, service, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := user.NewUserService(logger, userUseCase)
	httpServer := server.NewHTTPServer(bootstrap, service, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
