// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sunflower-blog-svc/app/blog/internal/biz"
	"sunflower-blog-svc/app/blog/internal/conf"
	"sunflower-blog-svc/app/blog/internal/data"
	"sunflower-blog-svc/app/blog/internal/server"
	"sunflower-blog-svc/app/blog/internal/service"
	"sunflower-blog-svc/app/blog/internal/service/mq"
	"sunflower-blog-svc/app/blog/internal/service/poster"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, jwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewPostgresDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger, jwt)
	userService := service.NewUserService(logger, userUseCase)
	posterRepo := data.NewPosterRepo(dataData, logger)
	posterUseCase := biz.NewPosterUseCase(posterRepo, logger)
	tagRepo := data.NewTagRepo(dataData, logger)
	tagUseCase := biz.NewTagUseCase(tagRepo, logger)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUseCase := biz.NewCategoryUseCase(categoryRepo, logger)
	senderFactory := mq.NewSenderFactory()
	posterService := poster.NewPosterService(posterUseCase, tagUseCase, categoryUseCase, senderFactory, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, posterService, logger)
	httpServer := server.NewHTTPServer(bootstrap, userService, posterService, logger)
	pageViewConsumer := mq.NewPageViewConsumer(posterUseCase)
	likeActionConsumer := mq.NewLikeActionConsumer()
	handlerRegistry := mq.NewHandlerRegistry(pageViewConsumer, likeActionConsumer)
	mqServer := server.NewMQServer(bootstrap, logger, handlerRegistry, senderFactory)
	app := newApp(logger, grpcServer, httpServer, mqServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
