// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sunflower-blog-svc/app/admin/internal/biz"
	"sunflower-blog-svc/app/admin/internal/conf"
	"sunflower-blog-svc/app/admin/internal/data"
	"sunflower-blog-svc/app/admin/internal/server"
	"sunflower-blog-svc/app/admin/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, jwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewPostgresDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger, jwt)
	userService := service.NewUserService(logger, userUseCase)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	posterClient, err := data.NewPosterServiceClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postRepo := data.NewPostRepo(posterClient, logger)
	postUseCase := biz.NewPostUseCase(postRepo, logger, jwt)
	posterService := service.NewPosterService(postUseCase, logger)
	httpServer := server.NewHTTPServer(bootstrap, userService, posterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
